// Generated file - DO NOT EDIT MANUALLY
// This file is automatically generated by Spider's generateEmbeddedTemplates
// Source directory: src/

pub const EmbeddedTemplates = struct {

    auth_login: []const u8 = @embedFile("features/auth/views/login.html"),
    games_index: []const u8 = @embedFile("features/games/views/index.html"),
    home_index: []const u8 = @embedFile("features/home/views/index.html"),
    todo_index: []const u8 = @embedFile("features/todo/views/index.html"),
    head: []const u8 = @embedFile("shared/templates/head.html"),
    layout: []const u8 = @embedFile("shared/templates/layout.html"),
    partials_navbar: []const u8 = @embedFile("shared/templates/partials/navbar.html"),
    partials_sidebar: []const u8 = @embedFile("shared/templates/partials/sidebar.html"),
    partials_spinner: []const u8 = @embedFile("shared/templates/partials/spinner.html"),

};
