// Generated file - DO NOT EDIT MANUALLY
// This file is automatically generated by Spider's generateEmbeddedTemplates
// Source directory: src/

pub const EmbeddedTemplates = struct {

    home_index: []const u8 = @embedFile("features/home/views/index.html"),
    auth_login: []const u8 = @embedFile("features/auth/views/login.html"),
    todo_item_todo: []const u8 = @embedFile("features/todo/views/item_todo.html"),
    todo_index: []const u8 = @embedFile("features/todo/views/index.html"),
    movies_index: []const u8 = @embedFile("features/movies/views/index.html"),
    movies_details: []const u8 = @embedFile("features/movies/views/details.html"),
    movies_search: []const u8 = @embedFile("features/movies/views/search.html"),
    movies_popular: []const u8 = @embedFile("features/movies/views/popular.html"),
    games_index: []const u8 = @embedFile("features/games/views/index.html"),
    games_modal_game: []const u8 = @embedFile("features/games/views/modal_game.html"),
    games_card_game: []const u8 = @embedFile("features/games/views/card_game.html"),
    layout: []const u8 = @embedFile("shared/templates/layout.html"),
    partials_bottom_nav: []const u8 = @embedFile("shared/templates/partials/bottom_nav.html"),
    partials_sidebar: []const u8 = @embedFile("shared/templates/partials/sidebar.html"),
    partials_topbar: []const u8 = @embedFile("shared/templates/partials/topbar.html"),
    partials_drawer: []const u8 = @embedFile("shared/templates/partials/drawer.html"),

};
